# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      core_tag_pattern:
        required: true
        default: 'M\.3\.[0-9A-Z]*\.[0-9]*'
      
env:
  CONTAINER_NAME_ADMIN: commerce-admin
  CONTAINER_NAME_STORE: commerce-store
  CONTAINER_NAME_LAYER: commerce-layer
  ACR_URL: linxcommerce.azurecr.io
  
  # verificar meio de obter via parâmetro/variável de ambiente posteriormente:
  TAG_BASELINE: CORE-3333

jobs:

  resolveTag:
    name: Resolve tag
    runs-on: ubuntu-latest
    
    outputs:
      new-tag: ${{ steps.checkout.outputs.new-tag }}
    
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with: 
          ref: main
        run: |
          echo new-tag=$(git describe --tags --abbrev=0 --match M\.3\.[0-9A-Z]*\.[0-9]* | awk -F"." '{$NF+=1}{print $0RT}' OFS="." ORS="") >> $GITHUB_OUTPUT
          
  createRelease:
    name: Create Release
    needs: resolveTag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.resolveTag.new-tag }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.resolveTag.new-tag }}
          release_name: Release ${{ needs.resolveTag.new-tag }}
          draft: false
          prerelease: false
