# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      core_tag_pattern:
        required: true
        default: 'M\.3\.[0-9A-Z]*\.[0-9]*'
      
env:
  CONTAINER_NAME_ADMIN: commerce-admin
  CONTAINER_NAME_STORE: commerce-store
  CONTAINER_NAME_LAYER: commerce-layer
  ACR_URL: linxcommerce.azurecr.io
  
  # verificar meio de obter via parâmetro/variável de ambiente posteriormente:
  TAG_BASELINE: CORE-3333

jobs:

  resolveTag:
    name: Resolve tag
    runs-on: ubuntu-latest
    
    outputs:
      new-tag: ${{ steps.resolve-tag.outputs.new-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: main
          fetch-depth: 0
      - run: |
          echo TARGET_TAG=$(git describe --tags --abbrev=0 --match M\.3\.[0-9A-Z]*\.[0-9]* | awk -F"." '{$NF+=1}{print $0RT}' OFS="." ORS="") >> $GITHUB_ENV
          #echo ${{ env.TARGET_TAG }}
          #echo "Branch Taging: ${{ env.TARGET_TAG }}"
          #echo "git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks tag -a -m "Github actions Tag" ${{ env.TARGET_TAG }}"
          #git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks tag -a -m "Github actions Tag" ${{ env.TARGET_TAG }}
          #echo "Branch Taged: ${{ env.TARGET_TAG }}"
          
      #- name: Resolve new tag
      #  id: resolve-tag
      #  run: |
      #    echo new-tag=$(git describe --tags --abbrev=0 --match M\.3\.[0-9A-Z]*\.[0-9]* | awk -F"." '{$NF+=1}{print $0RT}' OFS="." ORS="") >> $GITHUB_OUTPUT
      
      #- name: Push tag
      #  run: |
      #    echo "Branch Taging: ${{steps.resolve-tag.outputs.new-tag}}"
      #    echo "git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks tag -a -m "Github actions Tag" ${{steps.resolve-tag.outputs.new-tag}}"
      #    git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks tag -a -m "Github actions Tag" ${{steps.resolve-tag.outputs.new-tag}}
      #    echo "Branch Taged: ${{steps.resolve-tag.outputs.new-tag}}"
          
  createRelease:
    name: Create Release
    needs: resolveTag
    runs-on: ubuntu-latest
    
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2
      #  with:
      #    fetch-depth: 0
      #    ref: ${{ needs.resolveTag.outputs.new-tag }}
      - name: Tag Info
        run: echo ${{TARGET_TAG}}
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          tag_name: ${{ env.TARGET_TAG }}
          release_name: Release ${{ env.TARGET_TAG }}
          draft: false
          prerelease: false
