# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      core_tag_pattern:
        required: true
        default: 'M\.3\.[0-9A-Z]*\.[0-9]*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get lastest tag for pattern
        run: NEW_VERSION = $(git describe --tags --abbrev=0 --match M\.3\.[0-9A-Z]*\.[0-9]* | \
              gawk -F"." '{$NF+=1}{print $0RT}' OFS="." ORS="")
        #run: git tag -l
      - name: Test
        run: |
          echo $NEW_VERSION
