# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      core_tag_pattern:
        required: true
        default: 'M\.3\.[0-9A-Z]*\.[0-9]*'

jobs:
  generate-next-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
        name: Get lastest tag for pattern
      - run: echo new-version=$(git describe --tags --abbrev=0 --match M\.3\.[0-9A-Z]*\.[0-9]* | awk -F"." '{$NF+=1}{print $0RT}' OFS="." ORS="") >> $GITHUB_OUTPUT
        id: get-last-tag
      - name: Echo new-version
        run: |
          echo ${{ steps.get-last-tag.new-version }}
